// Publications dataset — extracted verbatim from the reference files in
// publications/*.html (one file per research area). Generated by
// scripts/extract-publications.mjs; edit the source HTML and re-run rather than
// hand-editing this file.

export type Publication = {
  facultyKey: string;
  facultyName: string;
  title: string;
  venue: string;
  authors: string;
  award?: string | null;
  areaSlug: string;
};

export const publications: Publication[] = [
  {
    "facultyKey": "ruozhou",
    "facultyName": "Ruozhou Yu",
    "title": "Traffic engineering in large-scale networks with generalizable graph neural networks.",
    "venue": "IEEE Transactions on Networking (2026).",
    "authors": "Zhou, Fangtong, Sihao Liu, Xiaorui Liu, Ruozhou Yu, and Guoliang Xue.",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "ruozhou",
    "facultyName": "Ruozhou Yu",
    "title": "Wormholes in Space: Unveiling Wormhole Attack in Low Earth Orbit Satellite Networks.",
    "venue": "In 2026 International Conference on Computing, Networking and Communications (ICNC), pp. 491-497. IEEE, 2026.",
    "authors": "Wang, Xiaojian, Ruozhou Yu, and Dejun Yang.",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "ruozhou",
    "facultyName": "Ruozhou Yu",
    "title": "Space Booking: Enabling Performance-Critical Applications in Broadband Satellite Networks.",
    "venue": "In 2025 IEEE 45th International Conference on Distributed Computing Systems (ICDCS), pp. 989-999. IEEE, 2025.",
    "authors": "Wang, Xiaojian, Ruozhou Yu, Dejun Yang, Guoliang Xue, Qiushi Wei, Huayue Gu, and Zhouyu Li.",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "ruozhou",
    "facultyName": "Ruozhou Yu",
    "title": "Robust resource provisioning in time-varying edge networks.",
    "venue": "In Proceedings of the Twenty-First International Symposium on Theory, Algorithmic Foundations, and Protocol Design for Mobile Networks and Mobile Computing, pp. 21-30. 2020.",
    "authors": "Yu, Ruozhou, Guoliang Xue, Yinxin Wan, Jian Tang, Dejun Yang, and Yusheng Ji.",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "ruozhou",
    "facultyName": "Ruozhou Yu",
    "title": "HSDRAN: Hierarchical software-defined radio access network for distributed optimization.",
    "venue": "IEEE Transactions on Vehicular Technology 67, no. 9 (2018): 8623-8636.",
    "authors": "Yu, Ruozhou, Guoliang Xue, Mehdi Bennis, Xianfu Chen, and Zhu Han.",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "mihail",
    "facultyName": "Mihail Sichitu",
    "title": "ACHEM: A Real-Time Digital Twin Framework with Channel and Radio Emulation.",
    "venue": "arXiv preprint arXiv:2604.04742, 2026.",
    "authors": "A. Gurses, M. L. Sichitiu.",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "mihail",
    "facultyName": "Mihail Sichitu",
    "title": "Real-World LoRaWAN Performance and Propagation Modeling Using UAV, Helikite, and Vehicle-Based Measurements.",
    "venue": "In Proc. IEEE Aerospace Conference, Big Sky, MT, Mar. 2026.",
    "authors": "S. V. Villar, S. Singh, O. Ozdemir, M. L. Sichitiu, and I. Guvenc.",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "mihail",
    "facultyName": "Mihail Sichitu",
    "title": "Demonstration of an Interactive Search and Rescue Scenario in AERPAW.",
    "venue": "In Proc. IEEE Military Commun. Conf. (MILCOM), Los Angeles, CA, Oct. 2025.",
    "authors": "J. Kesler, A. Gürses, O. Özdemir, M. Mushi, M. L. Sichitiu, I. Güvenç, R. Dutta, Vuk Marojevic.",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "mihail",
    "facultyName": "Mihail Sichitu",
    "title": "Digital Twins and Testbeds for Supporting AI Research with Autonomous Vehicle Networks.",
    "venue": "IEEE Commun. Mag., 2024.",
    "authors": "A. Gurses, G. Reddy, S. Masrur, O. Ozdemir, I. Guvenc, M. L. Sichitiu, A. Sahin, A. Alkhateeb, M. Mushi, and R. Dutta.",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "mihail",
    "facultyName": "Mihail Sichitu",
    "title": "Air-to-ground channel modeling for UAVs in rural areas.",
    "venue": "In Proc. IEEE 100th Vehicular Technology Conference (VTC2024-Fall), 1-6.",
    "authors": "A. Gürses, M. L. Sichitiu.",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "yuchen",
    "facultyName": "Yuchen Liu",
    "title": "Network Digital Untwinning: Towards Backward Optimization of Digital Twins.",
    "venue": "IEEE International Conference on Distributed Computing Systems (ICDCS), 2026.",
    "authors": "Z. Zhang, D. Chen, A. Gao, M. Wang, M. Chen, M. Fang, X. Yang, and Y. Liu.",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "yuchen",
    "facultyName": "Yuchen Liu",
    "title": "Contextual Combinatorial Beam Management via Online Probing for Multiple Access mmWave Wireless Networks.",
    "venue": "IEEE Journal on Selected Areas in Communications (JSAC), 2025.",
    "authors": "Z. Li, X. Luo, M. Chen, C. Xu, S. Mao, and Y. Liu.",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "yuchen",
    "facultyName": "Yuchen Liu",
    "title": "Digital Twin-Assisted Data-Driven Optimization for Reliable Edge Caching in Wireless Networks.",
    "venue": "IEEE Journal on Selected Areas in Communications (JSAC), 2024.",
    "authors": "Z. Zhang, Y. Liu, Z. Peng, M. Chen, D. Xu, and S. Cui.",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "yuchen",
    "facultyName": "Yuchen Liu",
    "title": "Map-Driven mmWave Link Quality Prediction with Spatial-Temporal Mobility Awareness.",
    "venue": "IEEE Transactions on Mobile Computing (TMC), 2024.",
    "authors": "Z. Li, M. Chen, G. Li, X. Lin, and Y. Liu.",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "yuchen",
    "facultyName": "Yuchen Liu",
    "title": "Agentic Open RAN: A Deterministic and Auditable Framework for Intent-Driven Radio Control.",
    "venue": "IEEE International Conference on Communications (ICC), 2026.",
    "authors": "H. Li, D. Xu, M. Chen, and Y. Liu.",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "wenye",
    "facultyName": "Wenye Wang",
    "title": "UNI-FI: Integrated Multi-Task Wi-Fi Sensing.",
    "venue": "IEEE INFOCOM 2026 - IEEE Conference on Computer Communications, Tokyo, Japan, 2026, pp. 1-10.",
    "authors": "Mengning Li and Wenye Wang.",
    "award": "Best Paper Award",
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "wenye",
    "facultyName": "Wenye Wang",
    "title": "Synergizing Acoustic and Wi-Fi Signals for Device-Free Gesture Recognition.",
    "venue": "In IEEE Transactions on Mobile Computing, vol. 24, no. 9, pp. 8167-8179, Sept. 2025.",
    "authors": "Mengning Li and Wenye Wang.",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "wenye",
    "facultyName": "Wenye Wang",
    "title": "mSAC: Enhancing Localization with mmWave Sensing and Orthogonal Signals.",
    "venue": "IEEE INFOCOM 2025 - IEEE Conference on Computer Communications, London, United Kingdom, 2025, pp. 1-10.",
    "authors": "Mengning Li, Haochen Zhu, Wenye Wang, and Eylem Ekici.",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "wenye",
    "facultyName": "Wenye Wang",
    "title": "FLuMe: Understanding Differential Spectrum Mobility Features in High Resolution.",
    "venue": "In IEEE Transactions on Mobile Computing, vol. 23, no. 12, pp. 14186-14200, Dec. 2024.",
    "authors": "Rui Zou and Wenye Wang.",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "wenye",
    "facultyName": "Wenye Wang",
    "title": "Hybrid Zone: Bridging Acoustic and Wi-Fi for Enhanced Gesture Recognition.",
    "venue": "IEEE INFOCOM 2024 - IEEE Conference on Computer Communications, Vancouver, BC, Canada, 2024, pp. 981-990.",
    "authors": "Mengning Li and Wenye Wang.",
    "award": "Best Paper Award",
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "ismail",
    "facultyName": "Ismail Guvenc",
    "title": "Small Cell Networks: Deployment, PHY Techniques, and Resource Management.",
    "venue": "Cambridge University Press, April 2013.",
    "authors": "T. Q. S. Quek, G. de la Roche, I. Guvenc, and M. Kountouris (Editors).",
    "award": "Book Edition",
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "ismail",
    "facultyName": "Ismail Guvenc",
    "title": "UAV Communications for 5G and Beyond.",
    "venue": "IEEE-Wiley, Feb. 2021.",
    "authors": "Y. Zeng, I. Guvenc, R. Zhang, G. Geraci, and D. Matolak (Editors).",
    "award": "Book Edition",
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "ismail",
    "facultyName": "Ismail Guvenc",
    "title": "UAV-Based 3D Spectrum Sensing Using Kriging and Matrix Completion: Insights on Altitude, Bandwidth, Trajectory, and Antenna Patterns.",
    "venue": "IEEE Sensors, May 2026.",
    "authors": "M. Rahman, S. J. Maeng, I. Guvenc, C. W. Wong, M. L. Sichitiu, J. A. Abrahamson, and A. Bhuyan.",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "ismail",
    "facultyName": "Ismail Guvenc",
    "title": "Reliability of Wi-Fi, LTE, and 5G-Based UAV RC Links in ISM Bands: Uplink Interference Asymmetry Analysis and HARQ Design.",
    "venue": "IEEE Open J. Commun. Systems, Aug. 2025.",
    "authors": "D. Lee, S. J. Maeng, O. Ozdemir, M. B. Pandian, and I. Guvenc.",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "ismail",
    "facultyName": "Ismail Guvenc",
    "title": "Energy-Efficient Sleep Mode Optimization in 5G mmWave Networks via Multi-Agent Deep Reinforcement Learning.",
    "venue": "IEEE Trans. Green Commun. Netw., Dec. 2025.",
    "authors": "S. Masrur, I. Guvenc, and D. Lopez-Perez.",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "vijay",
    "facultyName": "Vijay K. Shah",
    "title": "O-DSS: An Open Dynamic Spectrum Sharing Framework for Cellular-Radar Coexistence in Mid-band Frequencies.",
    "venue": "IEEE INFOCOM 2026 - IEEE Conference on Computer Communications (pp. 1-10)(to appear). Preprint available at arXiv:2601.02571.",
    "authors": "Chiejina, A., Muruganandham, D., Chaudhary, V., Chowdhury, K., & Shah, V. K. (2026).",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "vijay",
    "facultyName": "Vijay K. Shah",
    "title": "Black-Box Evasion Attacks on Data-Driven Open RAN Apps: Tailored Design and Experimental Evaluation.",
    "venue": "Proceedings of the ACM on Networking, 3(CoNEXT4), 1-26, 2025.",
    "authors": "Gajjar, P., Khoja, M., Ganiyu, A., Juarez, M., Marina, M. K., Lehane, A., & Shah, V. K. (2025).",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "vijay",
    "facultyName": "Vijay K. Shah",
    "title": "AI5GTest: AI-Driven Specification-Aware Automated Testing and Validation of 5G O-RAN Components.",
    "venue": "In the 18th ACM Conference on Security and Privacy in Wireless and Mobile Networks (pp. 53-64), June 2025.",
    "authors": "Ganiyu, A., Gajjar, P., & Shah, V. K. (2025).",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "vijay",
    "facultyName": "Vijay K. Shah",
    "title": "SenseORAN: O-RAN-Based Radar Detection in the CBRS Band.",
    "venue": "IEEE Journal on Selected Areas in Communications, vol. 42, no. 2, pp. 326-338, Feb. 2024.",
    "authors": "Guillem Reus-Muns, Pratheek S. Upadhyaya, Utku Demir, Nathan Stephenson, Nasim Soltani, Vijay K. Shah, and Kaushik R. Chowdhury.",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "vijay",
    "facultyName": "Vijay K. Shah",
    "title": "SPARC: Spatio-Temporal Adaptive Resource Control for Multi-site Spectrum Management in NextG Cellular Networks.",
    "venue": "Proceedings of the ACM on Networking, 2(CoNEXT4), 1-18, 2024.",
    "authors": "Ghosh, U., Chiejina, A., Stephenson, N., Shah, V. K., Shakkottai, S., & Bharadia, D. (2024).",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "dara",
    "facultyName": "Dara Ron",
    "title": "Intelligent Energy Efficiency and Service Reliability Optimization for UAV-Aided Terrestrial Networks.",
    "venue": "IEEE Transactions on Green Communications and Networking, 2026.",
    "authors": "D. Ron and J. -R. Lee.",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "dara",
    "facultyName": "Dara Ron",
    "title": "Time-Dependent Network Topology Optimization for LEO Satellite Constellations.",
    "venue": "IEEE INFOCOM 2025 - IEEE Conference on Computer Communications, 2025.",
    "authors": "D. Ron, F. A. Yusufzai, S. Kwakye, S. Roy, N. Sastry and V. K. Shah.",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "dara",
    "facultyName": "Dara Ron",
    "title": "Wireless-Powered Multi-Channel Backscatter Communications Under Jamming: A Cooperative Reinforcement Learning Approach.",
    "venue": "WiseML '24.",
    "authors": "Dara Ron and Kai Zeng.",
    "award": "Best Paper Award",
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "dara",
    "facultyName": "Dara Ron",
    "title": "Deep Reinforcement Learning-Based Active Sensing on a Bicycle for Vehicle Tracking.",
    "venue": "IEEE Transactions on Instrumentation and Measurement, vol. 75, pp. 1-14, 2026.",
    "authors": "W. Jeon, D. Ron and J. -R. Lee.",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "dara",
    "facultyName": "Dara Ron",
    "title": "DNN-Based Dynamic Transmit Power Control for V2V Communication Underlaid Cellular Uplink.",
    "venue": "IEEE Transactions on Vehicular Technology, Nov. 2022.",
    "authors": "D. Ron and J. -R. Lee.",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "huaiyu",
    "facultyName": "Huaiyu Dai",
    "title": "Robustness in Wireless Distributed Learning: An Information-Theoretic Analysis.",
    "venue": "IEEE Trans. Communications, vol. 73, no. 11, pp. 11243-11258, Nov. 2025.",
    "authors": "Y. He, G. Yu, and H. Dai.",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "huaiyu",
    "facultyName": "Huaiyu Dai",
    "title": "Speeding Up Distributed Learning via Sparse and Flexible Coded Computing.",
    "venue": "IEEE Trans. Information Theory, vol. 71, no. 4, pp. 3167-3180, Apr. 2025.",
    "authors": "J. Zhang, X. He, and H. Dai.",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "huaiyu",
    "facultyName": "Huaiyu Dai",
    "title": "Reinforcement Learning-Based Personalized Differentially Private Federated Learning.",
    "venue": "IEEE Trans. Information Forensics and Security, vol. 20, pp. 465-477, 2025.",
    "authors": "X. Lu, Z. Liu, L. Xiao, and H. Dai.",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "huaiyu",
    "facultyName": "Huaiyu Dai",
    "title": "Resource Constrained Vehicular Edge Federated Learning with Highly Mobile Connected Vehicles.",
    "venue": "IEEE Journal on Selected Areas in Communications, vol. 41, no. 6, pp. 1825-1844, Jun. 2023.",
    "authors": "M. F. Pervej, R. Jin, and H. Dai.",
    "award": null,
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "huaiyu",
    "facultyName": "Huaiyu Dai",
    "title": "Multi-Stage Hybrid Federated Learning over Large-Scale Wireless Fog Networks.",
    "venue": "IEEE Trans. Networking, vol. 30, no. 4, pp. 1569-1584, Aug. 2022.",
    "authors": "S. Hosseinalipour, S. S. Azam, C. G. Brinton, N. Michelusi, V. Aggarwal, D. J. Love, and H. Dai.",
    "award": "IEEE Communications Society William R. Bennett Prize",
    "areaSlug": "intelligent-wireless-networking-distributed-systems"
  },
  {
    "facultyKey": "vijay",
    "facultyName": "Vijay K. Shah",
    "title": "TeleResilienceBench: Quantifying Resilience for LLM Reasoning in Telecommunications.",
    "venue": "arXiv preprint arXiv:2605.09929, 2026.",
    "authors": "Gajjar, P., Ojo, E., & Shah, V. K.",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "vijay",
    "facultyName": "Vijay K. Shah",
    "title": "Advanced AI Service Provisioning in O-RAN through LLM Engine Integration.",
    "venue": "arXiv preprint arXiv:2605.23809, 2026.",
    "authors": "Natanzi, S. B. H., Gajja, P., Tang, B., & Shah, V. K.",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "vijay",
    "facultyName": "Vijay K. Shah",
    "title": "TeleEmbedBench: A Multi-Corpus Embedding Benchmark for RAG in Telecommunications.",
    "venue": "arXiv preprint arXiv:2604.17778, 2026.",
    "authors": "Gajjar, P., & Shah, V. K.",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "vijay",
    "facultyName": "Vijay K. Shah",
    "title": "Enhancing Confidence Estimation in Telco LLMs via Twin-Pass CoT-Ensembling.",
    "venue": "IEEE Vehicular Technology Conference (VTC), 2026 (to appear). Preprint available at arXiv:2604.13271.",
    "authors": "Saenko, A., Gajjar, P., Ganiyu, A., & Shah, V. K.",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "vijay",
    "facultyName": "Vijay K. Shah",
    "title": "Oransight-2.0: Foundational LLMs for O-RAN.",
    "venue": "IEEE Transactions on Machine Learning in Communications and Networking, 2025.",
    "authors": "Gajjar, P., & Shah, V. K.",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "yuchen",
    "facultyName": "Yuchen Liu",
    "title": "Generative Artificial Intelligence Models for Emerging Communication Systems: Fundamentals and Challenges.",
    "venue": "IEEE Communications Magazine (COMMAG), 2025.",
    "authors": "Z. Peng, Y. Liu, G. Li, Z. Yang, M. Chen, D. Xu, and X. Lin",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "yuchen",
    "facultyName": "Yuchen Liu",
    "title": "Graph Neural Networks for the Optimization of Collaborative Federated Learning Energy Efficiency.",
    "venue": "IEEE Transactions on Mobile Computing (TMC), 2025.",
    "authors": "N. Yang, S. Wang, Y. Liu, C. Brinton, C. Yin, and M. Chen",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "yuchen",
    "facultyName": "Yuchen Liu",
    "title": "Denoising Diffusion Probabilistic Model for Radio Map Estimation in Generative Wireless Networks.",
    "venue": "IEEE Transactions on Cognitive Communications and Networking (TCCN), 2025.",
    "authors": "X. Luo, Z. Li, Z. Peng, M. Chen, and Y. Liu",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "yuchen",
    "facultyName": "Yuchen Liu",
    "title": "Synergizing AI and Digital Twins for Next Generation Network Optimization, Forecasting, and Security.",
    "venue": "IEEE Wireless Communications (WCM), 2025.",
    "authors": "Z. Zhang, M. Fang, D. Chen, X. Yang, and Y. Liu",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "yuchen",
    "facultyName": "Yuchen Liu",
    "title": "Revolutionizing Wireless Modeling and Simulation with Network-Oriented LLMs.",
    "venue": "IEEE International Performance Computing and Communications Conference (IPCCC), 2024.",
    "authors": "J. Liu, Z. Peng, D. Xu, and Y. Liu",
    "award": "Best Paper Award Runner-up",
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "hamid",
    "facultyName": "Hamid Krim",
    "title": "Geometry via Vision Transformer: Learning by Proximal Updates.",
    "venue": "Submitted to Signal Processing Journal, 2026 (under review).",
    "authors": "H. Yun, E. Chouzenoux, B. Jiang, J.C. Pesquet, H. Krim",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "hamid",
    "facultyName": "Hamid Krim",
    "title": "Volterra Neural Networks: A New Perspective on Learning.",
    "venue": "Journal of Machine Learning Research, 2024.",
    "authors": "S. Roheda and H. Krim",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "hamid",
    "facultyName": "Hamid Krim",
    "title": "Deep transform and metric learning network: Wedding deep dictionary learning and neural network.",
    "venue": "Neurocomputing, 509: 244-256, 2022.",
    "authors": "W. Tang, É. Chouzenoux, J.C. Pesquet, and H. Krim",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "hamid",
    "facultyName": "Hamid Krim",
    "title": "Robustness Reprogramming for Representation Learning.",
    "venue": "International Conference on Learning Representations (ICLR), Singapore, 2025.",
    "authors": "Z. Hou, M. Torkamani, H. Krim, X. Liu",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "hamid",
    "facultyName": "Hamid Krim",
    "title": "Koopcon: A new approach towards smarter and less complex learning.",
    "venue": "International Conference on Image Processing (ICIP), Abu Dhabi, 2024.",
    "authors": "V. Jebraeeli, B. Jiang, D. Cansever, H. Krim",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "tianfu",
    "facultyName": "Tianfu Wu",
    "title": "WeGeFT: Weight-Generative Fine-Tuning for Multi-Faceted Efficient Adaptation of Large Models.",
    "venue": "International Conference on Machine Learning (ICML), 2025.",
    "authors": "Savadikar, Chinmay and Song, Xi and Wu, Tianfu",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "tianfu",
    "facultyName": "Tianfu Wu",
    "title": "HarmonyGNNs: Harmonizing Heterophily and Homophily in GNNs via Joint Structural Node Encoding and Self-Supervised Learning.",
    "venue": "International Conference on Learning Representations (ICLR), 2026.",
    "authors": "Xue, Rui and Wu, Tianfu",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "tianfu",
    "facultyName": "Tianfu Wu",
    "title": "CHEEM: Continual Learning by Reuse, New, Adapt and Skip-- A Hierarchical Exploration-Exploitation Approach.",
    "venue": "IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR), 2026.",
    "authors": "Savadikar, Chinmay and Dai, Michelle and Wu, Tianfu",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "tianfu",
    "facultyName": "Tianfu Wu",
    "title": "Adversarial Perturbations Are Formed by Iteratively Learning Linear Combinations of the Right Singular Vectors of the Adversarial Jacobian.",
    "venue": "International Conference on Machine Learning (ICML), 2025.",
    "authors": "Paniagua, Thomas and Savadikar, Chinmay and Wu, Tianfu",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "tianfu",
    "facultyName": "Tianfu Wu",
    "title": "PaCa-ViT: Learning Patch-to-Cluster Attention in Vision Transformers.",
    "venue": "IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR), 2023.",
    "authors": "Grainger, Ryan and Paniagua, Thomas and Song, Xi and Cuntoor, Naresh and Lee, Mun Wai and Wu, Tianfu",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "chauwai",
    "facultyName": "Chau-Wai Wong",
    "title": "SCALE: Towards collaborative content analysis in social science with large language model agents and human intervention.",
    "venue": "Annual Meeting of the Association for Computational Linguistics (ACL), Vienna, Austria, 2025.",
    "authors": "C. Zhao, Z. Tan, C.-W. Wong, X. Zhao, T. Chen, and H. Liu",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "chauwai",
    "facultyName": "Chau-Wai Wong",
    "title": "Serving multicultural publics: Assessing the role of dialogic communication and cultural tailoring strategies of GenAI chatbots in government OPRs for disasters.",
    "venue": "28th International Public Relations Research Conference (IPRRC), Orlando, FL, 2025.",
    "authors": "W. Liu, X. Zhao, Y. Sun, and C.-W. Wong",
    "award": "Boston University Award for Top Paper",
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "chauwai",
    "facultyName": "Chau-Wai Wong",
    "title": "PortLLM: Personalizing evolving large language models with training-free and portable model patches.",
    "venue": "International Conference on Learning Representations (ICLR), Singapore, 2025.",
    "authors": "R. M. Shahroz Khan, P. Li, S. Yun, Z. Wang, S. Nirjon, C.-W. Wong, and T. Chen",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "chauwai",
    "facultyName": "Chau-Wai Wong",
    "title": "NTK-DFL: Enhancing decentralized federated learning in heterogeneous settings via neural tangent kernel.",
    "venue": "International Conference on Machine Learning (ICML), Vancouver, Canada, 2025.",
    "authors": "G. Thompson, K. Yue, C.-W. Wong, and H. Dai",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "chauwai",
    "facultyName": "Chau-Wai Wong",
    "title": "Neural tangent kernel empowered federated learning.",
    "venue": "International Conference on Machine Learning (ICML), Baltimore, MD, 2022.",
    "authors": "K. Yue, R. Jin, R. Pilgrim, C.-W. Wong, D. Baron, H. Dai",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "huaiyu",
    "facultyName": "Huaiyu Dai",
    "title": "Noisy SIGNSGD Is More Differentially Private Than You (Might) Think.",
    "venue": "International Conference on Machine Learning (ICML), Vancouver, Canada, 2025.",
    "authors": "R. Jin and H. Dai",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "huaiyu",
    "facultyName": "Huaiyu Dai",
    "title": "GSBAK: Top-K Geometric Score-based Black-box Attack.",
    "venue": "International Conference on Learning Representations (ICLR), Singapore, 2025.",
    "authors": "M. F. Reza, R. Jin, T. Wu, and H. Dai",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "huaiyu",
    "facultyName": "Huaiyu Dai",
    "title": "Breaking the Communication-Privacy-Accuracy Tradeoff with f-Differential Privacy.",
    "venue": "Proceedings of the 37th International Conference on Neural Information Processing Systems (NeurIPS), New Orleans, LA, 2023.",
    "authors": "R. Jin, Z. Su, C. Zhong, Z. Zhang, T. Quek, and H. Dai",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "huaiyu",
    "facultyName": "Huaiyu Dai",
    "title": "Gradient Obfuscation Gives a False Sense of Security in Federated Learning.",
    "venue": "USENIX Security Symposium, Anaheim, CA, 2023.",
    "authors": "K. Yue, R. Jin, C. Wong, D. Baron, and H. Dai",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "huaiyu",
    "facultyName": "Huaiyu Dai",
    "title": "Graph Neural Networks Meet Wireless Communications: Motivation, Applications, and Future Directions.",
    "venue": "IEEE Wireless Communications, vol. 29, no. 5, pp. 12-19, 2022.",
    "authors": "M. Lee, G. Yu, H. Dai, and G. Y. Li",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "xiaorui",
    "facultyName": "Xiaorui Liu",
    "title": "Traffic Engineering in Large-scale Networks with Generalizable Graph Neural Networks.",
    "venue": "IEEE Transactions on Networking (ToN), 2026.",
    "authors": "Sihao Liu, Fangtong Zhou, Xiaorui Liu, Ruozhou Yu, Guoliang Xue",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "xiaorui",
    "facultyName": "Xiaorui Liu",
    "title": "Harnessing Trust in Directed Graphs: Redefining Robustness of Graph Learning.",
    "venue": "ACM Transactions on Knowledge Discovery from Data (TKDD), 2026.",
    "authors": "Zhichao Hou, Xitong Zhang, Wei Wang, Charu Aggarwal, Xiaorui Liu",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "xiaorui",
    "facultyName": "Xiaorui Liu",
    "title": "Modulated Diffusion: Accelerating Generative Modeling with Modulated Quantization.",
    "venue": "International Conference on Machine Learning (ICML), 2025.",
    "authors": "Weizhi Gao, Zhichao Hou, Junqi Yin, Feiyi Wang, Linyu Peng, Xiaorui Liu",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "xiaorui",
    "facultyName": "Xiaorui Liu",
    "title": "Efficient End-to-end Language Model Fine-tuning on Graphs.",
    "venue": "ACM International Conference on Knowledge Discovery & Data Mining (KDD), 2025.",
    "authors": "Rui Xue, Xipeng Shen, Ruozhou Yu, Xiaorui Liu",
    "award": null,
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "xiaorui",
    "facultyName": "Xiaorui Liu",
    "title": "Robustness Reprogramming for Representation Learning.",
    "venue": "International Conference on Learning Representations (ICLR), 2025.",
    "authors": "Zhichao Hou, MohamadAli Torkamani, Hamid Krim, Xiaorui Liu",
    "award": "Spotlight Paper",
    "areaSlug": "ai-foundations-learning"
  },
  {
    "facultyKey": "wenye",
    "facultyName": "Wenye Wang",
    "title": "UNI-FI: Integrated Multi-Task Wi-Fi Sensing",
    "venue": "IEEE INFOCOM 2026 - IEEE Conference on Computer Communications, Tokyo, Japan, pp. 1-10, 2026.",
    "authors": "Mengning Li and Wenye Wang",
    "award": "Best Paper Award",
    "areaSlug": "sensing-perception-integrated-intelligence"
  },
  {
    "facultyKey": "wenye",
    "facultyName": "Wenye Wang",
    "title": "Synergizing Acoustic and Wi-Fi Signals for Device-Free Gesture Recognition",
    "venue": "IEEE Transactions on Mobile Computing, vol. 24, no. 9, pp. 8167-8179, Sept. 2025.",
    "authors": "Mengning Li and Wenye Wang",
    "award": null,
    "areaSlug": "sensing-perception-integrated-intelligence"
  },
  {
    "facultyKey": "wenye",
    "facultyName": "Wenye Wang",
    "title": "mSAC: Enhancing Localization with mmWave Sensing and Orthogonal Signals",
    "venue": "IEEE INFOCOM 2025 - IEEE Conference on Computer Communications, London, United Kingdom, pp. 1-10, 2025.",
    "authors": "Mengning Li, Haochen Zhu, Wenye Wang, and Eylem Ekici",
    "award": null,
    "areaSlug": "sensing-perception-integrated-intelligence"
  },
  {
    "facultyKey": "wenye",
    "facultyName": "Wenye Wang",
    "title": "FLuMe: Understanding Differential Spectrum Mobility Features in High Resolution",
    "venue": "IEEE Transactions on Mobile Computing, vol. 23, no. 12, pp. 14186-14200, Dec. 2024.",
    "authors": "Rui Zou and Wenye Wang",
    "award": null,
    "areaSlug": "sensing-perception-integrated-intelligence"
  },
  {
    "facultyKey": "wenye",
    "facultyName": "Wenye Wang",
    "title": "Hybrid Zone: Bridging Acoustic and Wi-Fi for Enhanced Gesture Recognition",
    "venue": "IEEE INFOCOM 2024 - IEEE Conference on Computer Communications, Vancouver, BC, Canada, pp. 981-990, 2024.",
    "authors": "Mengning Li and Wenye Wang",
    "award": "Best Paper Award",
    "areaSlug": "sensing-perception-integrated-intelligence"
  },
  {
    "facultyKey": "ismail",
    "facultyName": "Ismail Guvenc",
    "title": "Ultra-Wideband Positioning Systems- Theoretical Limits, Ranging Algorithms, and Protocols",
    "venue": "Cambridge University Press, Book Monograph, Aug. 2008.",
    "authors": "Z. Sahinoglu, S. Gezici, and I. Guvenc",
    "award": null,
    "areaSlug": "sensing-perception-integrated-intelligence"
  },
  {
    "facultyKey": "ismail",
    "facultyName": "Ismail Guvenc",
    "title": "A Survey on TOA Based Wireless Localization and NLOS Mitigation Techniques",
    "venue": "IEEE Communications Surveys and Tutorials, vol. 11, no. 3, pp. 107-124, July 2009.",
    "authors": "I. Guvenc and C. C. Chong",
    "award": null,
    "areaSlug": "sensing-perception-integrated-intelligence"
  },
  {
    "facultyKey": "ismail",
    "facultyName": "Ismail Guvenc",
    "title": "Detection and Classification of UAVs Using RF Fingerprints in the Presence of Interference",
    "venue": "IEEE Open Journal of the Communications Society, Jan. 2020.",
    "authors": "M. Ezuma, F. Erden, C. K. Anjinappa, O. Ozdemir, and I. Guvenc",
    "award": null,
    "areaSlug": "sensing-perception-integrated-intelligence"
  },
  {
    "facultyKey": "ismail",
    "facultyName": "Ismail Guvenc",
    "title": "Leveraging Cellular ISAC and Passive RF Sensing for UAV Detection and Tracking",
    "venue": "Proceedings of the IEEE Asilomar Conference, Pacific Grove, CA, Oct. 2025.",
    "authors": "C. Dickerson, S. Kearney, S. Manjur, I. Guvenc, S. Gurbuz, A. Gurbuz, O. Ozdemir, and M. Sichitiu",
    "award": null,
    "areaSlug": "sensing-perception-integrated-intelligence"
  },
  {
    "facultyKey": "ismail",
    "facultyName": "Ismail Guvenc",
    "title": "A Survey on Detection, Classification, and Tracking of Aerial Threats using Radar and Communications Systems",
    "venue": "IEEE Communications Surveys and Tutorials, 2024.",
    "authors": "W. Khawaja, M. Ezuma, V. Semkin, F. Erden, O. Ozdemir, and I. Guvenc",
    "award": null,
    "areaSlug": "sensing-perception-integrated-intelligence"
  },
  {
    "facultyKey": "sevgi",
    "facultyName": "Sevgi Z. Gurbuz",
    "title": "Physics-Guided Deep Neural Networks for Radar-Based UAV Recognition in Different Environments With No Prior In Situ Data",
    "venue": "IEEE Transactions on Aerospace and Electronic Systems, vol. 62, pp. 9875-9891, 2026.",
    "authors": "S. Kearney and S. Z. Gurbuz",
    "award": null,
    "areaSlug": "sensing-perception-integrated-intelligence"
  },
  {
    "facultyKey": "sevgi",
    "facultyName": "Sevgi Z. Gurbuz",
    "title": "Human-Centered Fully Adaptive Radar for Gesture Recognition in Smart Environments",
    "venue": "IEEE Transactions on Human-Machine Systems, vol. 55, no. 5, pp. 695-706, Oct. 2025.",
    "authors": "E. Kurtoğlu and S. Z. Gurbuz",
    "award": null,
    "areaSlug": "sensing-perception-integrated-intelligence"
  },
  {
    "facultyKey": "sevgi",
    "facultyName": "Sevgi Z. Gurbuz",
    "title": "CV-SincNet: Learning Complex Sinc Filters From Raw Radar Data for Computationically Efficient Human Motion Recognition",
    "venue": "IEEE Transactions on Radar Systems, vol. 1, pp. 493-504, 2023.",
    "authors": "S. Biswas, C. O. Ayna, S. Z. Gurbuz and A. C. Gurbuz",
    "award": null,
    "areaSlug": "sensing-perception-integrated-intelligence"
  },
  {
    "facultyKey": "sevgi",
    "facultyName": "Sevgi Z. Gurbuz",
    "title": "Physics-Aware Generative Adversarial Networks for Radar-Based Human Activity Recognition",
    "venue": "IEEE Transactions on Aerospace and Electronic Systems, vol. 59, no. 3, pp. 2994-3008, June 2023.",
    "authors": "M. M. Rahman, S. Z. Gurbuz and M. G. Amin",
    "award": null,
    "areaSlug": "sensing-perception-integrated-intelligence"
  },
  {
    "facultyKey": "sevgi",
    "facultyName": "Sevgi Z. Gurbuz",
    "title": "American Sign Language Recognition Using RF Sensing",
    "venue": "IEEE Sensors Journal, vol. 21, no. 3, pp. 3763-3775, Feb. 2021.",
    "authors": "S. Z. Gurbuz et al.",
    "award": null,
    "areaSlug": "sensing-perception-integrated-intelligence"
  },
  {
    "facultyKey": "vijay",
    "facultyName": "Vijay K. Shah",
    "title": "CellSense: A Sub-6 GHz Cellular ISAC System for Clutter-Robust Passive Sensing",
    "venue": "IEEE Military Communications Conference (MILCOM), 2026 (Under review).",
    "authors": "Bibhor Kumar, Ish Jain, and Vijay K. Shah",
    "award": null,
    "areaSlug": "sensing-perception-integrated-intelligence"
  },
  {
    "facultyKey": "vijay",
    "facultyName": "Vijay K. Shah",
    "title": "Experimental Validation of a 3GPP compliant 5G-based Positioning System",
    "venue": "Proceedings of the 30th Annual International Conference on Mobile Computing and Networking (MobiCom), pp. 1946-1953, 2024.",
    "authors": "Sarik Dhungel, Gaurav Duggal, Dara Ron, Nishith D. Tripathi, R. M. Buehrer, J. H. Reed, and Vijay K. Shah",
    "award": null,
    "areaSlug": "sensing-perception-integrated-intelligence"
  },
  {
    "facultyKey": "suresh",
    "facultyName": "Suresh Venkatesh",
    "title": "I2SAC: AI-enabled Digital-Twin Framework on a mmWave 64-element Phased Array for Integrated Imaging, Sensing, and Communication",
    "venue": "International Microwave Symposium (IMS), RFSA, 2026 (Accepted)",
    "authors": "V. Reddy, J. Sober, L. Hogan, and S. Venkatesh",
    "areaSlug": "communication-systems-hardware-platforms"
  },
  {
    "facultyKey": "suresh",
    "facultyName": "Suresh Venkatesh",
    "title": "Physical Layer Security Through Directional Modulation With Spatio-Temporal Millimeter-Wave Transmitter Arrays",
    "venue": "IEEE Journal of Solid-State Circuits, vol. 59, no. 9, pp. 2831-2847, Sept. 2024",
    "authors": "X. Lu, S. Venkatesh, B. Tang and K. Sengupta",
    "areaSlug": "communication-systems-hardware-platforms"
  },
  {
    "facultyKey": "brian",
    "facultyName": "Brian Floyd",
    "title": "39–44 GHz Phased-Array Transmitter Circuits in RFSOI CMOS Technology",
    "venue": "IEEE Journal of Solid-State Circuits, vol. 60, no. 9, pp. 3072-3081, Sept. 2025",
    "authors": "T. Ren, Y. Chang and B. A. Floyd",
    "areaSlug": "communication-systems-hardware-platforms"
  },
  {
    "facultyKey": "brian",
    "facultyName": "Brian Floyd",
    "title": "A mmWave Software-Defined Array Platform for Wireless Experimentation at 24-29.5 GHz",
    "venue": "MILCOM 2024 - 2024 IEEE Military Communications Conference, pp. 1-6, 2024",
    "authors": "A. P. Ganesh, A. Perre, A. Şahin, İ. Güvenç and B. A. Floyd",
    "areaSlug": "communication-systems-hardware-platforms"
  },
  {
    "facultyKey": "yuan",
    "facultyName": "Yuan Liu",
    "title": "Toward mixed analog-digital quantum signal processing: Quantum ad/da conversion and the fourier transform",
    "venue": "IEEE Transactions on Signal Processing, 2025",
    "authors": "Liu, Yuan, John M. Martyn, Jasmine Sinanan-Singh, Kevin C. Smith, Steven M. Girvin, and Isaac L. Chuang",
    "areaSlug": "communication-systems-hardware-platforms"
  },
  {
    "facultyKey": "alexandra",
    "facultyName": "Alexandra Duel-Hallen",
    "title": "Early Warning of mmWave Signal Blockage Using Diffraction Properties and Machine Learning",
    "venue": "IEEE Communications Letters, vol. 26, no. 12, pp. 2944-2948, Dec. 2022",
    "authors": "A. Fallah Dizche, A. Duel-Hallen and H. Hallen",
    "areaSlug": "communication-systems-hardware-platforms"
  },
  {
    "facultyKey": "alexandra",
    "facultyName": "Alexandra Duel-Hallen",
    "title": "Impact of Reflectors and MIMO on ML-Aided mmWave/sub-THz Blockage Prediction",
    "venue": "IEEE 23rd Consumer Communications & Networking Conference (CCNC), pp. 1-6, 2026",
    "authors": "R. Mahdavihaji, A. Duel-Hallen and H. Hallen",
    "areaSlug": "communication-systems-hardware-platforms"
  },
  {
    "facultyKey": "alexandra",
    "facultyName": "Alexandra Duel-Hallen",
    "title": "Early Warning of mmWave Signal Blockage and AoA Transition Using sub-6 GHz Observations",
    "venue": "IEEE Communications Letters, vol. 24, no. 1, pp. 207-211, Jan. 2020",
    "authors": "Z. Ali, A. Duel-Hallen and H. Hallen",
    "areaSlug": "communication-systems-hardware-platforms"
  },
  {
    "facultyKey": "ismail",
    "facultyName": "Ismail Guvenc",
    "title": "Coverage Enhancement for NLOS mmWave Links Using Passive Reflectors",
    "venue": "IEEE Open Journal of the Communications Society, Feb. 2020",
    "authors": "W. A. G. Khawaja, O. Ozdemir, Y. Yapici, F. Erden, and I. Guvenc",
    "areaSlug": "communication-systems-hardware-platforms"
  },
  {
    "facultyKey": "ismail",
    "facultyName": "Ismail Guvenc",
    "title": "Base Station and Passive Reflectors Placement for Urban mmWave Networks",
    "venue": "IEEE Transactions on Vehicular Technology, Feb. 2021",
    "authors": "C. K. Anjinappa, F. Erden, and I. Guvenc",
    "areaSlug": "communication-systems-hardware-platforms"
  },
  {
    "facultyKey": "ismail",
    "facultyName": "Ismail Guvenc",
    "title": "Propagation Measurements and Coverage Analysis for mmWave and Sub-THz Frequency Bands with Transparent Reflectors",
    "venue": "Proceedings of the IEEE Vehicular Technology Conference (VTC), June 2023",
    "authors": "A. P. Ganesh, W. Khawaja, O. Ozdemir, and I. Guvenc",
    "areaSlug": "communication-systems-hardware-platforms"
  },
  {
    "facultyKey": "ismail",
    "facultyName": "Ismail Guvenc",
    "title": "Coverage Probability Analysis of Passive Reflectors in Indoor Environments",
    "venue": "IEEE Communications Letters, July 2022",
    "authors": "S. J. Maeng, C. K. Anjinappa, I. Guvenc",
    "areaSlug": "communication-systems-hardware-platforms"
  },
  {
    "facultyKey": "ismail",
    "facultyName": "Ismail Guvenc",
    "title": "Precoder Design for Physical-Layer Security and Authentication in Massive MIMO UAV Communications",
    "venue": "IEEE Transactions on Vehicular Technology, Dec. 2021",
    "authors": "S. J. Maeng, Y. Yapici, I. Guvenc, A. Bhuyan, and H. Dai",
    "areaSlug": "communication-systems-hardware-platforms"
  },
  {
    "facultyKey": "huaiyu",
    "facultyName": "Huaiyu Dai",
    "title": "Deep Reinforcement Learning for AoI-Aware Trajectory and Phase-shift Design in IRS-Assisted UAV Data Collection",
    "venue": "IEEE Transactions on Wireless Communications, vol. 24, no. 12, pp. 10613-10628, Dec. 2025",
    "authors": "J. Tang, J. Liu, X. He, L. Xie, L. Qu, and H. Dai",
    "areaSlug": "communication-systems-hardware-platforms"
  },
  {
    "facultyKey": "huaiyu",
    "facultyName": "Huaiyu Dai",
    "title": "Base Station Antenna Uptilt Optimization for Cellular-Connected Drone Corridors",
    "venue": "IEEE Transactions on Aerospace and Electronic Systems, vol. 59, no. 4, pp. 4729-4737, Aug. 2023",
    "authors": "S. J. Maeng, M. Chowdhury, I. Guvenc, A. Bhuyan, and H. Dai",
    "areaSlug": "communication-systems-hardware-platforms"
  },
  {
    "facultyKey": "huaiyu",
    "facultyName": "Huaiyu Dai",
    "title": "Optimal Relay Probing for UAV Millimeter Wave Communications with Beam Training Overhead",
    "venue": "IEEE Transactions on Vehicular Technology, vol. 72, no. 6, pp. 7351-7363, Jun. 2023",
    "authors": "Z. Song, J. An, H. Ding, and H. Dai",
    "areaSlug": "communication-systems-hardware-platforms"
  },
  {
    "facultyKey": "huaiyu",
    "facultyName": "Huaiyu Dai",
    "title": "Hybrid Beamforming and Adaptive RF Chain Activation for Cell-Free Millimeter-Wave Massive MIMO Systems",
    "venue": "IEEE Transactions on Vehicular Technology, vol. 71, no. 8, pp. 8739-8755, Aug. 2022",
    "authors": "N. Nguyen, K. Lee, and H. Dai",
    "areaSlug": "communication-systems-hardware-platforms"
  },
  {
    "facultyKey": "huaiyu",
    "facultyName": "Huaiyu Dai",
    "title": "Application of Deep Learning to Sphere Decoding for Large MIMO Systems",
    "venue": "IEEE Transactions on Wireless Communications, vol. 20, no. 10, pp. 6787-6803, Oct. 2021",
    "authors": "N. Nguyen, K. Lee, and H. Dai",
    "areaSlug": "communication-systems-hardware-platforms"
  },
  {
    "facultyKey": "jake",
    "facultyName": "Jake Adams",
    "title": "Multipath-Enhanced Measurement of Antenna Patterns: Experiment",
    "venue": "IEEE Transactions on Antennas and Propagation, 2026 (Early Access)",
    "authors": "D. D. Stancil, A. R. Allen, M. Ptak and J. J. Adams",
    "areaSlug": "communication-systems-hardware-platforms"
  },
  {
    "facultyKey": "jake",
    "facultyName": "Jake Adams",
    "title": "Shape Synthesis and 3-D Ceramic Printing of Non-Canonical MIMO Dielectric Resonator Antennas",
    "venue": "IEEE Open Journal of Antennas and Propagation, vol. 6, no. 6, pp. 1763-1772, Dec. 2025",
    "authors": "B. Yang, J. Kim, T. Bellundagi and J. J. Adams",
    "areaSlug": "communication-systems-hardware-platforms"
  },
  {
    "facultyKey": "jake",
    "facultyName": "Jake Adams",
    "title": "An Efficient Method for Complex Digitally Coded Antenna Design Based on Evolutionary Computation and Machine Learning Techniques",
    "venue": "IEEE Transactions on Antennas and Propagation, vol. 73, no. 12, pp. 9734-9747, Dec. 2025",
    "authors": "T. Wu, B. Liu, Q. Hua, M. O. Akinsolu, D. P. Buch, and J. J. Adams",
    "areaSlug": "communication-systems-hardware-platforms"
  },
  {
    "facultyKey": "jake",
    "facultyName": "Jake Adams",
    "title": "Analysis and Correction of Focal Plane Distortion in Flattened Luneburg Lenses",
    "venue": "IEEE Antennas and Wireless Propagation Letters, vol. 24, no. 10, pp. 3719-3723, Oct. 2025",
    "authors": "H. Askari, Y. Oh and J. Adams",
    "areaSlug": "communication-systems-hardware-platforms"
  },
  {
    "facultyKey": "jake",
    "facultyName": "Jake Adams",
    "title": "Limits in Spectral Efficiency From Array Geometry",
    "venue": "IEEE Journal on Selected Areas in Information Theory, vol. 6, pp. 34-48, 2025",
    "authors": "D. Badheka, J. J. Adams and B. L. Hughes",
    "areaSlug": "communication-systems-hardware-platforms"
  },
  {
    "facultyKey": "zhishan",
    "facultyName": "Zhishan Guo",
    "title": "Jointly Ensuring Timing Disparity and End-to-End Latency Constraints in Hybrid DAGs",
    "venue": "The 31st IEEE Real-Time and Embedded Technology and Applications Symposium (RTAS), Irvine, US, May 2025.",
    "authors": "Jinghao Sun, Xisheng Li, Mingyang Gong, Nan Guan, Zhishan Guo, Mingsong Chen, Jun Zhao, Qingxu Deng",
    "award": "Outstanding Paper Award",
    "areaSlug": "autonomous-systems-applications"
  },
  {
    "facultyKey": "zhishan",
    "facultyName": "Zhishan Guo",
    "title": "Estimation of Lower Extremity Joint Moments and 3D Ground Reaction Forces Using IMU Sensors in Multiple Walking Conditions: A Deep Learning Approach",
    "venue": "IEEE Journal of Biomedical and Health Informatics, 27(6): 2829-2840, June 2023.",
    "authors": "Md Sanzid Bin Hossain, Zhishan Guo and Hwan Choi",
    "award": null,
    "areaSlug": "autonomous-systems-applications"
  },
  {
    "facultyKey": "zhishan",
    "facultyName": "Zhishan Guo",
    "title": "SEAM: An Optimal Message Synchronizer in ROS with Well-Bounded Time Disparity",
    "venue": "2023 IEEE Real-Time Systems Symposium (RTSS), Taipei, December 2023.",
    "authors": "Jinghao Sun, Tianyi Wang, Yang Li, Nan Guan, Zhishan Guo, Qingxu Deng, Guozhen Tan",
    "award": "Best Paper Award",
    "areaSlug": "autonomous-systems-applications"
  },
  {
    "facultyKey": "zhishan",
    "facultyName": "Zhishan Guo",
    "title": "Efficient Feasibility Analysis for Graph-based Real-Time Task Systems",
    "venue": "International Conference on Embedded Software (EMSOFT), September 2020, pp. 3385-3397.",
    "authors": "Jinghao Sun, Rongxiao Shi, Kexuan Wang, Nan Guan and Zhishan Guo",
    "award": "Best Paper Award",
    "areaSlug": "autonomous-systems-applications"
  },
  {
    "facultyKey": "zhishan",
    "facultyName": "Zhishan Guo",
    "title": "Mixed-Criticality Multicore Scheduling of Real-Time Gang Task Systems",
    "venue": "2019 IEEE Real-Time Systems Symposium (RTSS), Hong Kong, December 2019, pp. 469-480.",
    "authors": "Ashikahmed Bhuiyan, Kecheng Yang, Samsil Arefin, Abusayeed Saifullah, Nan Guan and Zhishan Guo",
    "award": "Outstanding Paper Award, Best Student Paper Award",
    "areaSlug": "autonomous-systems-applications"
  },
  {
    "facultyKey": "jaemin",
    "facultyName": "Jaemin Lee",
    "title": "A data-driven method for safety-critical control: Designing control barrier functions from state constraints",
    "venue": "2024 American Control Conference (ACC). IEEE, 2024.",
    "authors": "Lee, Jaemin, Jeeseop Kim, and Aaron D. Ames",
    "award": null,
    "areaSlug": "autonomous-systems-applications"
  },
  {
    "facultyKey": "jaemin",
    "facultyName": "Jaemin Lee",
    "title": "Safety-critical control of quadrupedal robots with rolling arms for autonomous inspection of complex environments",
    "venue": "2024 IEEE International Conference on Robotics and Automation (ICRA), pp. 3485-3491. IEEE, 2024.",
    "authors": "Lee, Jaemin, Jeeseop Kim, Wyatt Ubellacker, Tamas G. Molnar, and Aaron D. Ames",
    "award": null,
    "areaSlug": "autonomous-systems-applications"
  },
  {
    "facultyKey": "jaemin",
    "facultyName": "Jaemin Lee",
    "title": "Hierarchical relaxation of safety-critical controllers: Mitigating contradictory safety conditions with application to quadruped robots",
    "venue": "2023 IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS). IEEE, 2023.",
    "authors": "Lee, Jaemin, Jeeseop Kim, and Aaron D. Ames",
    "award": null,
    "areaSlug": "autonomous-systems-applications"
  },
  {
    "facultyKey": "jaemin",
    "facultyName": "Jaemin Lee",
    "title": "Real-Time Model Predictive Control for Industrial Manipulators with Singularity-Tolerant Hierarchical Task Control",
    "venue": "2023 IEEE International Conference on Robotics and Automation (ICRA), pp. 12282-12288. IEEE, 2023.",
    "authors": "Lee, Jaemin, Mingyo Seo, Andrew Bylard, Robert Sun, and Luis Sentis",
    "award": null,
    "areaSlug": "autonomous-systems-applications"
  },
  {
    "facultyKey": "jaemin",
    "facultyName": "Jaemin Lee",
    "title": "Dynamic locomotion for passive-ankle biped robots and humanoids using whole-body locomotion control",
    "venue": "The International Journal of Robotics Research 39, no. 8 (2020): 936-956.",
    "authors": "Kim, Donghyun, Steven Jens Jorgensen, Jaemin Lee, Junhyeok Ahn, Jianwen Luo, and Luis Sentis",
    "award": null,
    "areaSlug": "autonomous-systems-applications"
  },
  {
    "facultyKey": "alper",
    "facultyName": "Alper Bozkurt",
    "title": "A multimodal sensing platform for interdisciplinary research in agrarian environments",
    "venue": "Sensors, 22(15), p.5582. DOI: 10.3390/s22155582, 2022.",
    "authors": "Reynolds, J., Williams, E., Martin, D., Readling, C., Ahmmed, P., Huseth, A. and Bozkurt, A.",
    "award": null,
    "areaSlug": "autonomous-systems-applications"
  },
  {
    "facultyKey": "alper",
    "facultyName": "Alper Bozkurt",
    "title": "Preliminary evaluation of a system with on-body and aerial sensors for monitoring working dogs",
    "venue": "Sensors, 22(19), p.7631. DOI: 10.3390/s22197631, 2022.",
    "authors": "Foster, M., Wu, T., Roberts, D.L. and Bozkurt, A.",
    "award": null,
    "areaSlug": "autonomous-systems-applications"
  },
  {
    "facultyKey": "alper",
    "facultyName": "Alper Bozkurt",
    "title": "Preliminary evaluation of dog-drone technological interfaces: Challenges and opportunities",
    "venue": "Proceedings of the Sixth International Conference on Animal-Computer Interaction (pp. 1-5). DOI: 10.1145/3371049.3371065, Nov. 2019.",
    "authors": "Foster, M., Agcayazi, T., Agcayazi, T., Wu, T., Gruen, M., Roberts, D.L. and Bozkurt, A.",
    "award": null,
    "areaSlug": "autonomous-systems-applications"
  },
  {
    "facultyKey": "alper",
    "facultyName": "Alper Bozkurt",
    "title": "Contact-free simultaneous sensing of human heart rate and canine breathing rate for animal assisted interactions",
    "venue": "Proceedings of the Ninth International Conference on Animal-Computer Interaction (pp. 1-10). DOI: 10.1145/3565995.3566039, Dec. 2022.",
    "authors": "Holder, T., Rahman, M., Summers, E., Roberts, D., Wong, C.W. and Bozkurt, A.",
    "award": null,
    "areaSlug": "autonomous-systems-applications"
  },
  {
    "facultyKey": "alper",
    "facultyName": "Alper Bozkurt",
    "title": "Noncontact electrophysiology monitoring systems for assessment of canine-human interactions",
    "venue": "2021 IEEE Sensors (pp. 1-4). DOI: 10.1109/SENSORS47087.2021.9639748, Oct. 2021.",
    "authors": "Ahmmed, P., Holder, T., Foster, M., Castro, I.D., Patel, A., Torfs, T. and Bozkurt, A.",
    "award": null,
    "areaSlug": "autonomous-systems-applications"
  },
  {
    "facultyKey": "hamid",
    "facultyName": "Hamid Krim",
    "title": "Information Fusion: Scaling Subspace Driven Approaches",
    "venue": "Submitted to IEEE Transactions on Image Processing, 2021.",
    "authors": "Sally Ghanem and Hamid Krim",
    "award": null,
    "areaSlug": "autonomous-systems-applications"
  },
  {
    "facultyKey": "hamid",
    "facultyName": "Hamid Krim",
    "title": "Atlantic Hurricane Activity Prediction: A Machine Learning Approach",
    "venue": "Journal of Atmosphere, Section Atmospheric Techniques, Instruments, and Modeling, Special Issue 'Recent Advances and Future Prospects of Machine Learning in Predictive Modeling of Atmospheric Sciences', 2021.",
    "authors": "T. Asthana, X. Sun, S. Roheda, L. Xie, and H. Krim",
    "award": null,
    "areaSlug": "autonomous-systems-applications"
  },
  {
    "facultyKey": "hamid",
    "facultyName": "Hamid Krim",
    "title": "Event Driven Sensor Fusion",
    "venue": "Elsevier Signal Processing, Volume 188, November 2021.",
    "authors": "S. Roheda, Z.-Q. Luo, T. Wu, and H. Krim",
    "award": null,
    "areaSlug": "autonomous-systems-applications"
  },
  {
    "facultyKey": "hamid",
    "facultyName": "Hamid Krim",
    "title": "Robust Multi-Modal Sensor Fusion: An Adversarial Approach",
    "venue": "IEEE Sensors Journal, 21(2): 1885-1896, 2020.",
    "authors": "S. Roheda, H. Krim, and B. S. Riggan",
    "award": null,
    "areaSlug": "autonomous-systems-applications"
  },
  {
    "facultyKey": "hamid",
    "facultyName": "Hamid Krim",
    "title": "Robust Group Subspace Recovery: A New Approach for Multi-Modality Data Fusion",
    "venue": "IEEE Sensors Journal, 2020.",
    "authors": "Sally Ghanem, Ashkan Panahi, Ryan A. Kerekes, and Hamid Krim",
    "award": null,
    "areaSlug": "autonomous-systems-applications"
  }
];
